export default function Lessons(){
  return (
    <div>
      <h2>Lessons</h2>
      <p>Daily micro-lessons generated by OpenAI + curriculum pacing. Check Practice to generate one now.</p>
    </div>
  )
}
